# Generated by Django 5.0.7 on 2024-08-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src_lang', models.CharField(max_length=20)),
                ('dst_lang', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('pdf_name', models.CharField(max_length=1255)),
                ('md', models.FileField(null=True, upload_to='mds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
