# Generated by Django 5.0.7 on 2024-08-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_translator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='translator',
            name='dst_lang',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='translator',
            name='md',
            field=models.FileField(blank=True, null=True, upload_to='mds/'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='src_lang',
            field=models.CharField(max_length=255),
        ),
    ]
