# Generated by Django 5.0.7 on 2024-08-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_translator', '0002_alter_translator_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='model_name',
            field=models.CharField(choices=[('4o-mini', '4o-mini'), ('3-turbo', '3-turbo')], null=True, verbose_name='model_name'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='dst_lang',
            field=models.CharField(max_length=255, verbose_name='destination language'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='md',
            field=models.FileField(blank=True, null=True, upload_to='mds/', verbose_name='markdown file'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='pdf',
            field=models.FileField(upload_to='pdfs/', verbose_name='pdf'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='pdf_name',
            field=models.CharField(max_length=1255, verbose_name='pdf file name'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='src_lang',
            field=models.CharField(max_length=255, verbose_name='source language'),
        ),
    ]
